theme: jekyll-theme-architect
title: Pratik Surela
email: surelapratik@gmail.com
description: This is a site for android tutorials where i can post modules on github and post how to use it.

skin: night # default, night, plum, sea, soft, steel
